

-- QUESTION 6 

CREATE TABLE STUDENT (STUID INT,FIRSTNAME VARCHAR(25),LASTNAME VARCHAR(25),WEBSITE VARCHAR(50),CITY VARCHAR(25))
INSERT INTO STUDENT VALUES (1011,'KEYUR','PATEL','TECHONTHENET.COM','RAJKOT')
INSERT INTO STUDENT VALUES (1022,'HARDIK','SHAH','DIGMINECRAFT.COM','AHMEDABAD')
INSERT INTO STUDENT VALUES (1033,'KAJAL','TRIVEDI','BIGACTIVITIES.COM','BARODA')
INSERT INTO STUDENT VALUES (1044,'BHOOMI','GAJERA','CHECKYOURMATH.COM','AHMEDABAD')
INSERT INTO STUDENT VALUES (1055,'HARMIT','MITEL',NULL,'RAJKOT')
INSERT INTO STUDENT VALUES (1066,'ASHOK','JANI',NULL,'BARODA')
update  student set website = null where website ='null'
SELECT * FROM STUDENT

--PART A

SELECT FIRSTNAME FROM STUDENT WHERE  FIRSTNAME  LIKE 'K%'
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '_____'
SELECT FIRSTNAME,LASTNAME FROM STUDENT WHERE CITY LIKE '_____A'
SELECT * FROM STUDENT WHERE LASTNAME LIKE '%TEL'
SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'HA%T'
SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'K%Y%'

--PART B

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '_____' AND WEBSITE is null 
SELECT * FROM STUDENT WHERE LASTNAME LIKE '%JER%'
SELECT * FROM STUDENT WHERE CITY LIKE 'R%' OR CITY LIKE 'B%'
select firstname from student where website is not null
select * from student where firstname like '[a-h]%'
select * from student where firstname like '_[a-e-i-o-u]%'


--part c

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '_____' AND WEBSITE is null 
select * from student where lastname like 'pat%'
select firstname,lastname from student where city not like 'b%'
select firstname,lastname from student where firstname like 'a%' or firstname like 'h%'
select * from student where firstname like '_[a-e-i-o-u]%' and firstname like'h%'

